// LOCALHOST USERS
### Get all users
Get http://localhost:8080/users

### Get user by id
GET http://localhost:8080/users/67cef3a286596de53be93212

### Create user
POST http://localhost:8080/users HTTP/1.1
content-type: application/json

{
    "_id": "67cef3a286596de53be93215",
    "userId": 7,
    "name": "Billy Bo Bob",
    "email": "Bill@example.com",
    "age": 100,
    "createdAt": "2024-03-01T11:50:00Z",
    "isActive": true,
    "roles": [
      "admin" ]
}

### Put user
PUT http://localhost:8080/users/67d45fb50cc45fea329520d2
content-type: application/json

{
    "_id": "67d45fb50cc45fea329520d2",
    "userId": 7,
    "name": "Cantakerous Sam",
    "email": "samIAM@example.com",
    "age": 1,
    "createdAt": "2025-03-14T16:56:21.991Z",
    "isActive": false,
    "roles": [
      "admin"]
}

### Delete user
DELETE http://localhost:8080/users/67d45fb50cc45fea329520d2






// LOCALHOST TRANSACTIONS
### Get all transactions
Get http://localhost:8080/transactions

### Get transaction by id
GET http://localhost:8080/transactions/67cef3bd86596de53be9321c

### Create transaction
POST http://localhost:8080/transactions HTTP/1.1
content-type: application/json

{
    "_id": "67cef3bd86596de53be9321c",
    "transactionId": 101,
    "userId": "67cef3a286596de53be9320f",
    "amount": 500.01,
    "currency": "USD",
    "type": "debit",
    "date": "2024-03-09T10:30:00Z",
    "status": "completed"
}

### Put transaction
PUT http://localhost:8080/transactions/67d460450cc45fea329520d3
content-type: application/json

{
    "_id": "67cef3bd86596de53be93221",
    "transactionId": 106,
    "userId": "67cef3a286596de53be93214",
    "amount": 300,
    "currency": "USD",
    "type": "debit",
    "date": "2024-03-04T08:20:00Z",
    "status": "pending"
}

### Delete transaction
DELETE http://localhost:8080/transactions/67d460450cc45fea329520d3

// LOCALHOST AUTHENTICATION (GITHUB OAUTH)
### GitHub OAuth Login
GET http://localhost:8080/auth/github

### GitHub OAuth Callback
GET http://localhost:8080/auth/github/callback

### Logout User
GET http://localhost:8080/auth/logout